### ISSUE TITLE
will it work for multivariate time series

### ISSUE THREAD

**Issue by Sandy4321** [ashsteel97/stocks-price-forecasting-apps-fts#1]
great code thanks
may you clarify : 
will it work for multivariate time series prediction   both regression and classification 
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by ashsteel97** [comment]
Hello @Sandy4321, sorry for the late reply
I'm very sorry to inform you that, currently this is only support for one variable time series data
The data used in this project is very limited due to the "data cleaning" process is build from investing.com (my main time series data source for this project)
I'm building this project mainly for my educational purpose only
As of now, personally  i highly recommend using python for multi variative data FTS, because as you may already know, python is very powerful language for data analytics and data visualization.
The algorithm in this project is based on Jens Runi Poulsen Proposed FTS Method
If you're interested to further developing this project, feel free to contact me again :)

**Comment by Sandy4321** [comment]
Jens Runi Poulsen Proposed FTS Method

Yes it is interesting
May you  share links to git hub code or any other material pls
